name: PR Workflow

on: [push,pull_request]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo"Hello from First Job:" 
  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo"bye from SEcond Job:"
